### ISSUE TITLE
swtpm 1.2 not working with qemu/libvirt, swtpm_setup exit status 1, no log created

### ISSUE THREAD

**Issue by norbert-kremeris-itdev** [stefanberger/swtpm#217] opened 2020-03-03 16:46 UTC
I have built and installed the master branches of both libtpms and swtpm with the options "--with-openssl" and "--with-tpm2". I have successfully tested that the tpm2.0 tis emulated model works with a redhat guest under libvirt/qemu, but swtpm_setup fails if i try to add a tpm 1.2 tis emulated model with the following error:

```
virsh # start rhel8.0-2
error: Failed to start domain rhel8.0-2
error: internal error: Could not run '/usr/bin/swtpm_setup'. exitstatus: 1; Check error log '/var/log/swtpm/libvirt/qemu/rhel8.0-2-swtpm.log' for details.
```
I can not perform any further debugging steps as the log file referenced by the error is not created by libvirt / swtpm when attempting to start the 1.2 tpm model. When starting a VM with the 2.0 model, the log file is created and is populated with the commands invocations and success messages:
```
Starting vTPM manufacturing as root:root @ Tue 03 Mar 2020 16:19:51 GMT
Successfully created EK with handle 0x81010001.
  Invoking: /usr/share/swtpm/swtpm-localca --type ek --ek "<..>" --dir "/var/lib/libvirt/swtpm/95f3a63f-622f-4b6a-af39-bc079f0049a2/tpm2" --logfile "/var/log/swtpm/libvirt/qemu/rhel8.0-2-swtpm.log" --vmid "rhel8.0-2:95f3a63f-622f-4b6a-af39-bc079f0049a2" --tpm-spec-family 2.0 --tpm-spec-level 00 --tpm-spec-revision 150 --tpm-manufacturer id:00001014 --tpm-model swtpm --tpm-version id:20170619 --configfile "/etc/swtpm-localca.conf" --optsfile "/etc/swtpm-localca.options" --tpm2
Successfully created EK certificate locally.
swtpm-localca: 
  Invoking: /usr/share/swtpm/swtpm-localca --type platform --ek "<...>" --dir "/var/lib/libvirt/swtpm/95f3a63f-622f-4b6a-af39-bc079f0049a2/tpm2" --logfile "/var/log/swtpm/libvirt/qemu/rhel8.0-2-swtpm.log" --vmid "rhel8.0-2:95f3a63f-622f-4b6a-af39-bc079f0049a2" --tpm-spec-family 2.0 --tpm-spec-level 00 --tpm-spec-revision 150 --tpm-manufacturer id:00001014 --tpm-model swtpm --tpm-version id:20170619 --configfile "/etc/swtpm-localca.conf" --optsfile "/etc/swtpm-localca.options" --tpm2
Successfully created platform certificate locally.
swtpm-localca: 
Successfully created NVRAM area 0x01c00002 for EK certificate.
Successfully created NVRAM area 0x01c08000 for platform certificate.
Successfully activated PCR banks sha256,sha1 among sha1,sha256,sha384,sha512.
Successfully authored TPM state.
```

Libvirt log is also completely useless:
```
sudo cat /var/log/libvirt/qemu/rhel8.0-2.log 
2020-03-03 16:44:38.209+0000: shutting down, reason=failed
```

I noticed that when running make check for swtpm, the tpm 1.2 test is skipped, but i am not sure if this is relevant to the problem:

```
SKIP: test_vtpm_proxy
SKIP: test_tpm2_vtpm_proxy
PASS: test_ctrlchannel4
PASS: test_ctrlchannel3
PASS: test_tpm2_ctrlchannel2
PASS: test_ctrlchannel2
PASS: test_ctrlchannel
PASS: test_getcap
PASS: test_hashing
PASS: test_locality
PASS: test_encrypted_state
PASS: test_hashing2
PASS: test_resume_volatile
PASS: test_migration_key
PASS: test_setbuffersize
PASS: test_save_load_state
PASS: test_save_load_encrypted_state
PASS: test_volatilestate
SKIP: test_tpm12
PASS: test_tpm_probe
PASS: test_print_capabilities
PASS: test_init
PASS: test_wrongorder
PASS: test_tpm2_derived_keys
PASS: test_swtpm_bios
PASS: test_tpm2_encrypted_state
PASS: test_tpm2_getcap
PASS: test_tpm2_locality
PASS: test_tpm2_hashing
PASS: test_tpm2_hashing3
PASS: test_tpm2_migration_key
PASS: test_tpm2_resume_volatile
PASS: test_tpm2_hashing2
SKIP: test_tpm2_save_load_state_3
PASS: test_tpm2_savestate
PASS: test_tpm2_init
PASS: test_tpm2_setbuffersize
PASS: test_tpm2_wrongorder
PASS: test_tpm2_volatilestate
PASS: test_tpm2_probe
SKIP: test_tpm2_ibmtss2
PASS: test_commandline
SKIP: test_parameters
PASS: test_swtpm_cert
SKIP: test_tpm2_parameters
PASS: test_tpm2_samples_swtpm_localca
SKIP: test_tpm2_samples_swtpm_localca_pkcs11
PASS: test_tpm2_swtpm_cert
PASS: test_tpm2_swtpm_cert_ecc
PASS: test_tpm2_swtpm_setup_create_cert
SKIP: test_swtpm_setup_create_cert
SKIP: test_samples_create_tpmca
PASS: test_tpm2_save_load_encrypted_state
PASS: test_tpm2_swtpm_bios
PASS: test_tpm2_save_load_state_da_timeout

```

Additional info:

Host OS is Ubuntu 19.10
Guest os is RHEL 8.

```
swtpm --version
TPM emulator version 0.3.0, Copyright (c) 2014 IBM Corp.
```

```
virsh # version
Compiled against library: libvirt 5.4.0
Using library: libvirt 5.4.0
Using API: QEMU 5.4.0
Running hypervisor: QEMU 4.0.0
```

**Comment by stefanberger** [comment] 2020-03-25 21:13
Can you show me the output of `./configure` when run for swtpm?

**Comment by stefanberger** [comment] 2020-03-25 21:19
What is the output of the last one of the following commands for you?

```
# mkdir -p /tmp/mytpm12
# sudo chown tss /tmp/mytpm12
# sudo swtpm_setup --tpmstate /tmp/mytpm12 --createek --create-platform-cert --overwrite
```

**Comment by jriwanek** [comment] 2020-03-30 04:15
Also, getting the same issues, response of the last command:

Starting vTPM manufacturing as tss:tss @ Sun 29 Mar 2020 09:14:05 PM PDT
TPM is listening on TCP port 49929.
Successfully created EK.
TSS is listening on TCP port 41271.
Successfully took ownership of the TPM.
  Invoking: /usr/share/swtpm/swtpm-localca --type platform --ek "bb4c55a962757df585c591df39910aac5bb7233ddc62d8a95037de74c1d9019701923c5fafc7e249ae900476fd35162031b3cb137228b4eba4a61c395d9e044aa4cf765c49b33a8e295e009663e8690128fac5e96dd9761f6612910f22b9a6f184210b41eebf5861d9b422aa5922713ac15ef1ee9c4f2c145c0f67edc29b0069ab80800d7d2b2bf00ecea506b0d50b52f9e3a4a55b2d83cf4b491fa658d30ac5107e10c5763e154bc11c0bbd720c253d990fddc1df171a7219dc8a2c0c2e00e06de82e5ef5017147fed386607d0f56daed613569abfba1dcb1d3b3d529eaa6d7747f5de8f304e9a17618dd8cbb9d8b4dd42a2d1cb076e0be9cfae84e0c0b9f83" --dir "/tmp/mytpm12" --tpm-spec-family 1.2 --tpm-spec-level 2 --tpm-spec-revision 116 --tpm-manufacturer id:00001014 --tpm-model swtpm --tpm-version id:00740001 --configfile "/etc/swtpm-localca.conf" --optsfile "/etc/swtpm-localca.options"
swtpm-localca: Creating root CA and a local CA's signing key and issuer cert.
swtpm-localca: Successfully created platform certificate locally.
Successfully created NVRAM area for platform certificate.
Successfully gave up ownership of the TPM.
Successfully enabled and activated the TPM

Successfully authored TPM state.
Ending vTPM manufacturing @ Sun 29 Mar 2020 09:14:10 PM PDT

**Comment by stefanberger** [comment] 2020-03-30 12:12
Can you try to put the AppArmor profile on libvirt in complain mode and try again?

**Comment by jriwanek** [comment] 2020-04-01 09:34
Swtpm log:

Starting vTPM manufacturing as tss:tss @ Wed 01 Apr 2020 02:33:23 AM PDT
Successfully created EK.
Successfully took ownership of the TPM.
  Invoking: /usr/share/swtpm/swtpm-localca --type ek --ek "96f1d81df2a95cec302485f14a86268e2c7ff784e68b05d8f0cd12d948bde0597cf7598e03f3c481c63d9e3460d877e27a6eda8cedf0f6cd5158239d7406b2b4d37b98e2917f01000139fe156de0f7f31a23d0c66504224a4bf1bff904f127141b4d54e7b856bce5e56f09d587c766c7549b7aedea60de5ba8be5e5a08c197cbda106b9c725d765fc05381c48a4ae18b16b14e062a5d5ea00d1bd9e3fc7aa6b8855d6a57964040286f057b717e866f6ce505fc8ba804119d0b66fa64c77e8e7753b8622f27699f6e0fad5d3736c9cc0833b3122634619b2284df201e97954f0ee1d8eb9bf1ee857f41c2724ade50691b3da0199a5b37fa980b93475bff4404cf" --dir "/var/lib/libvirt/swtpm/391308d5-a86f-42a6-a2ae-2800cd9eae64/tpm1.2" --logfile "/var/log/swtpm/libvirt/qemu/testing2-swtpm.log" --vmid "testing2:391308d5-a86f-42a6-a2ae-2800cd9eae64" --tpm-spec-family 1.2 --tpm-spec-level 2 --tpm-spec-revision 116 --tpm-manufacturer id:00001014 --tpm-model swtpm --tpm-version id:00740001 --configfile "/etc/swtpm-localca.conf" --optsfile "/etc/swtpm-localca.options"
Successfully created EK certificate locally.
swtpm-localca:
  Invoking: /usr/share/swtpm/swtpm-localca --type platform --ek "96f1d81df2a95cec302485f14a86268e2c7ff784e68b05d8f0cd12d948bde0597cf7598e03f3c481c63d9e3460d877e27a6eda8cedf0f6cd5158239d7406b2b4d37b98e2917f01000139fe156de0f7f31a23d0c66504224a4bf1bff904f127141b4d54e7b856bce5e56f09d587c766c7549b7aedea60de5ba8be5e5a08c197cbda106b9c725d765fc05381c48a4ae18b16b14e062a5d5ea00d1bd9e3fc7aa6b8855d6a57964040286f057b717e866f6ce505fc8ba804119d0b66fa64c77e8e7753b8622f27699f6e0fad5d3736c9cc0833b3122634619b2284df201e97954f0ee1d8eb9bf1ee857f41c2724ade50691b3da0199a5b37fa980b93475bff4404cf" --dir "/var/lib/libvirt/swtpm/391308d5-a86f-42a6-a2ae-2800cd9eae64/tpm1.2" --logfile "/var/log/swtpm/libvirt/qemu/testing2-swtpm.log" --vmid "testing2:391308d5-a86f-42a6-a2ae-2800cd9eae64" --tpm-spec-family 1.2 --tpm-spec-level 2 --tpm-spec-revision 116 --tpm-manufacturer id:00001014 --tpm-model swtpm --tpm-version id:00740001 --configfile "/etc/swtpm-localca.conf" --optsfile "/etc/swtpm-localca.options"
Successfully created platform certificate locally.
swtpm-localca:
Successfully created NVRAM area for EK certificate.
Successfully created NVRAM area for platform certificate.
Successfully locked NVRAM access.
Successfully gave up ownership of the TPM.
Successfully enabled and activated the TPM

Successfully authored TPM state.
Ending vTPM manufacturing @ Wed 01 Apr 2020 02:33:27 AM PDT

**Comment by jriwanek** [comment] 2020-04-01 09:35
VM log:

2020-04-01 09:33:27.253+0000: Starting external device: TPM Emulator
/usr/bin/swtpm socket --daemon --ctrl type=unixio,path=/var/run/libvirt/qemu/swtpm/17-testing2-swtpm.sock,mode=0600 --tpmstate dir=/var/lib/libvirt/swtpm/391308d5-a86f-42a6-a2ae-2800cd9eae64/tpm1.2,mode=0600 --log file=/var/log/swtpm/libvirt/qemu/testing2-swtpm.log --pid file=/var/run/libvirt/qemu/swtpm/17-testing2-swtpm.pid
2020-04-01 09:33:27.297+0000: shutting down, reason=failed

**Comment by jriwanek** [comment] 2020-04-01 09:36
/var/log/messages apparmor output:
Apr  1 02:33:27 gateway kernel: [476705.602475] audit: type=1400 audit(1585733607.291:224): apparmor="DENIED" operation="open" profile="libvirt-391308d5-a86f-42a6-a2ae-2800cd9eae64" name="/var/log/swtpm/libvirt/qemu/testing2-swtpm.log" pid=31615 comm="swtpm" requested_mask="c" denied_mask="c" fsuid=131 ouid=131

**Comment by jriwanek** [comment] 2020-04-01 09:37
I also tried with aa-disable /usr/sbin/libvirtd and other than no apparmor output, no change

**Comment by stefanberger** [comment] 2020-04-01 15:50
For the record: Libvirt received an AppArmor fix for TPM support that is available in libvirt 5.8.0 only. Though since you are telling me that you turned off AppArmor enforcement for libvirt, it must be something else then.
I will try to install Ubuntu 19.10.

**Comment by stefanberger** [comment] 2020-04-01 17:03
When I disable AppArmor on my 19.10 system entirely (`systemctl disable apparmor;reboot`) I can start a VM with an attached TPM 1.2 or TPM 2, otherwise neither TPM 1.2 nor TPM 2 work. Therefore, the issue is related to AppArmor and likely this version of libvirt needs to be patched with this patch here: https://libvirt.org/git/?p=libvirt.git;a=commit;h=d660dd95ea91839156eb078710e9d85a2f306ab5

**Comment by stefanberger** [comment] 2020-04-01 17:09
Ubuntu does not officially package swtpm and libtpms yet, so official vTPM support may not be there yet in Ubuntu and that may lower the chances of having libvirt 5.4.0 patched.

**Comment by jriwanek** [comment] 2020-04-03 20:01
Debian 10 in my case, For my own notes what --tpm params would you suggest? (Trying to get us all on the same page testing wise), I'll give that patch a go and let you know if it helps.

**Comment by stefanberger** [comment] 2020-04-03 20:49
I think that TPM support should just work once libvirt has that patch applied. No special parameters should be needed. Though I saw that they are applying lots of AppArmor related patches to libvirt 5.4.0 build: https://launchpad.net/ubuntu/+archive/primary/+sourcefiles/libvirt/5.4.0-0ubuntu5.2/libvirt_5.4.0-0ubuntu5.2.debian.tar.xz

[see directory debian\patches\ubuntu-aa\]
So building this from the libvirt sources and installing it will likely not produce something that's working. I had my challenges with this also when I wrote the initial patches for the aa-helper of libvirt.

It looks like libvirt 6.0.0 was built: https://launchpad.net/ubuntu/+source/libvirt/6.0.0-0ubuntu6

**Comment by stefanberger** [comment] 2020-04-24 17:58
Did you try libvirt 6.0.0 on Focal in the meantime. I would expect that this should resolve the issue.

**Comment by kailiu42** [comment] 2020-07-22 14:13
Hi, I'm having the same issue on openSUSE Tumbleweed. Software versions are:

- swtpm 0.3.2
- libvirt 6.5.0
- qemu 5.0.0

With a emulated TPM 2.0 device the VM can just start normally. But with a TPM 1.2 TIS device the VM cannot start, there is no log under `/var/log/swtpm/libvirt/qemu/`. AppArmor is disabled on this system so I think this issue might not be AppArmor related at all.

**Comment by stefanberger** [comment] 2020-07-22 14:20
Can you enable auditing on this machine and have a look at the audit log? Maybe there's something related to swtpm there.

**Comment by kailiu42** [comment] 2020-07-22 14:41
Here is the audit log when the virtual TPM device is 2.0:

```
type=VIRT_RESOURCE msg=audit(1595428200.082:327): pid=1900 uid=0 auid=4294967295 ses=4294967295 subj==unconfined msg='virt=kvm resrc=tpm-emulator reason=start vm="win10" uuid=51415125-1f0a-43de-92cf-000a5b39b630 device="/run/libvirt/qemu/swtpm/10-win10-swtpm.sock" exe="/usr/sbin/libvirtd" hostname=? addr=? terminal=? res=success'
```

And the log after changed to TPM 1.2:

```
type=VIRT_RESOURCE msg=audit(1595428702.635:345): pid=1900 uid=0 auid=4294967295 ses=4294967295 subj==unconfined msg='virt=kvm resrc=tpm-emulator reason=start vm="win10" uuid=51415125-1f0a-43de-92cf-000a5b39b630 device="?" exe="/usr/sbin/libvirtd" hostname=? addr=? terminal=? res=success'
```

**Comment by stefanberger** [comment] 2020-07-22 17:30
I currently do not have a physical machine with either Ubuntu or OpenSUSE to test this on. So I took an ec2 VM with Ubuntu Focal running a plain QEMU VM since (nested) KVM is not supported. I installed swtpm-tools from my PPA here: https://launchpad.net/~stefanberger/+archive/ubuntu/swtpm-focal

The following domain XML for a VM with TPM 1.2 attached started for me. I doesn't have a disk but this shouldn't matter since at least the start of the VM worked.

```
<domain type='qemu'>
  <name>testvm</name>
  <uuid>485d0004-a48f-436a-8457-8a3b73e28568</uuid>
  <memory unit='KiB'>2097152</memory>
  <currentMemory unit='KiB'>2097152</currentMemory>
  <vcpu placement='static'>4</vcpu>
  <resource>
    <partition>/machine</partition>
  </resource>
  <os>
    <type arch='x86_64' machine='pc-i440fx-focal'>hvm</type>
    <boot dev='hd'/>
    <bootmenu enable='yes'/>
  </os>
  <features>
    <acpi/>
    <apic/>
    <pae/>
  </features>
  <cpu mode='custom' match='exact' check='full'>
    <model fallback='forbid'>kvm64</model>
    <feature policy='require' name='hypervisor'/>
  </cpu>
  <clock offset='utc'>
    <timer name='rtc' tickpolicy='catchup'/>
    <timer name='pit' tickpolicy='delay'/>
    <timer name='hpet' present='no'/>
  </clock>
  <on_poweroff>destroy</on_poweroff>
  <on_reboot>restart</on_reboot>
  <on_crash>restart</on_crash>
  <pm>
    <suspend-to-mem enabled='yes'/>
    <suspend-to-disk enabled='yes'/>
  </pm>
  <devices>
    <emulator>/bin/qemu-system-x86_64</emulator>
    <controller type='usb' index='0' model='ich9-ehci1'>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x05' function='0x7'/>
    </controller>
    <controller type='usb' index='0' model='ich9-uhci1'>
      <master startport='0'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x05' function='0x0' multifunction='on'/>
    </controller>
    <controller type='usb' index='0' model='ich9-uhci2'>
      <master startport='2'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x05' function='0x1'/>
    </controller>
    <controller type='usb' index='0' model='ich9-uhci3'>
      <master startport='4'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x05' function='0x2'/>
    </controller>
    <controller type='ide' index='0'>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x01' function='0x1'/>
    </controller>
    <controller type='pci' index='0' model='pci-root'/>
    <interface type='network'>
      <mac address='52:54:00:ae:ac:e8'/>
      <source network='default'/>
      <model type='rtl8139'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x03' function='0x0'/>
    </interface>
    <input type='mouse' bus='usb'>
      <address type='usb' bus='0' port='1'/>
    </input>
    <input type='mouse' bus='ps2'/>
    <input type='keyboard' bus='ps2'/>
    <tpm model='tpm-tis'>
      <backend type='emulator' version='1.2'/>
    </tpm>
    <graphics type='vnc' port='-1' autoport='yes'>
      <listen type='address'/>
    </graphics>
    <video>
      <model type='cirrus' vram='16384' heads='1' primary='yes'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x02' function='0x0'/>
    </video>
    <memballoon model='virtio'>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x06' function='0x0'/>
    </memballoon>
  </devices>
</domain>
```

**Comment by stefanberger** [comment] 2020-07-22 17:40
@kailiu42 Can you post your domain XML and maybe try the one I posted?

**Comment by stefanberger** [comment] 2020-07-22 20:54
@jriwanek @norbert-kremeris-itdev Did you try this again with Ubuntu-Focal or a more recent version of libvirt? I cannot recreate the issue inside a VM running Ubuntu-Focal with plain QEMU (rather than KVM), so maybe the issues has been resolve on Ubuntu now?

**Comment by stefanberger** [comment] 2020-07-22 21:04
@kailiu42 Can you please open a new issue so that we can separate the issues by distro? Please state the version of Tumbleweed you are using. Thanks.

**Comment by kailiu42** [comment] 2020-07-23 09:43
> @kailiu42 Can you please open a new issue so that we can separate the issues by distro? Please state the version of Tumbleweed you are using. Thanks.

#284 created per your request. Domain XML was attached there.

**Comment by stefanberger** [comment] 2020-07-23 17:51
I just tried starting a VM with attached TPM 1.2 on Ubuntu Focal again and it worked for me using my PPA:

```
sudo add-apt-repository ppa:stefanberger/swtpm-focal
sudo apt-get update
sudo apt-get -y install swtpm-tools
```

I would say Ubuntu Focal (20.04) would be the first one to support.

**Comment by stefanberger** [comment] 2020-07-29 14:43
I am going to close this issue now assuming it works for everyone starting with Ubuntu Focal.

**Closed by stefanberger** 2020-07-29 14:43 UTC
Labels: Ubuntu
