### ISSUE TITLE
Windows arm64 virtual machine?

### ISSUE THREAD

**Issue by jeremyd2019** [stefanberger/swtpm#493] opened 2021-07-21 00:04 UTC
As you may have heard, Windows 11 is requiring the presence of TPM 2.0, and I'm trying to provide it one via qemu on aarch64.  I followed the instructions from https://qemu-project.gitlab.io/qemu/specs/tpm.html.

```
mkdir /tmp/mytpm1
swtpm socket --tpmstate dir=/tmp/mytpm1 \
  --ctrl type=unixio,path=/tmp/mytpm1/swtpm-sock \
  --log level=20
```

```
  -chardev socket,id=chrtpm,path=/tmp/mytpm1/swtpm-sock \
  -tpmdev emulator,id=tpm0,chardev=chrtpm \
  -device tpm-tis-device,tpmdev=tpm0 \
```

I saw #223 and updated to EDK2 that has TPM support, but Windows still shows that the TPM 2.0 device cannot start, The I/O device is configured incorrectly or the configuration parameters to the driver are incorrect.

Am I missing something?  I can see the swtpm log stuff during early boot, but nothing after

**Comment by stefanberger** [comment] 2021-07-21 00:56
I don't know much about Windows on aarch64. Maybe someone in the QEMU or edk2 community can help.

**Comment by stefanberger** [comment] 2021-07-21 01:08
You could post the log your are getting. **Maybe** something is visible there. You are using a recent QEMU and EDK2 (EDK2 from QEMU?), right?

**Comment by jeremyd2019** [comment] 2021-07-21 01:52
I was hoping there was something silly like "you need to run this script to initialize the TPM before Windows will like it" or something.  I'll try to record some logs later.  I am using [qemu-system-arm from debian bullseye](https://packages.debian.org/bullseye/qemu-system-arm), and just tried with the [qemu-efi-aarch64 from debian experimental](https://packages.debian.org/experimental/qemu-efi-aarch64) to be sure it was built with TPM2 and secure boot (including MS keys pre-enrolled)

**Comment by stefanberger** [comment] 2021-07-21 02:20
You could try to add running `swtpm_setup` like in the following commands so that the vTPM has platform and EK certificates, though I would not expect this to solve what you are reporting as "The I/O device is configured incorrectly or the configuration parameters to the driver are incorrect."

```
mkdir /tmp/mytpm1
swtpm_setup --tpmstate /tmp/myvtpm1 --create-ek-cert --create-platform-cert --tpm2 --overwrite
swtpm socket --tpmstate dir=/tmp/mytpm1 \
  --ctrl type=unixio,path=/tmp/mytpm1/swtpm-sock \
  --log level=20
```

**Comment by jeremyd2019** [comment] 2021-07-21 05:36
OK, here's the output from swtpm socket, and a screenshot of the device manager error.  This is after using swtpm_setup this time


[swtpm_log.txt](https://github.com/stefanberger/swtpm/files/6853066/swtpm.txt)

![2021-07-20-222814_1024x768_scrot](https://user-images.githubusercontent.com/4524874/126436431-aa940c3c-539f-4d81-aba0-3ef31671e490.png)

**Comment by jeremyd2019** [comment] 2021-07-21 05:38
I did notice that qemu in bullseye is at 5.2 not 6.0, so *maybe* a newer qemu would help, but I somehow doubt it.

**Comment by stefanberger** [comment] 2021-07-21 11:32
regarding the log: The log ends with a bunch of PCR_Extends. The PCR_Extends seem to even touch PCRs 10-14, which is a bit unusual. What I am missing also is that EDK2 sets ownership of the platform hierarchy.

I would work my way backwards from the latest QEMU + accompanying EDK2.

**Comment by jeremyd2019** [comment] 2021-07-21 18:01
I get the same results with both qemu-system-arm and qemu-efi-aarch64 from debian experimental.

[swtpm-experimental.txt](https://github.com/stefanberger/swtpm/files/6857913/swtpm-experimental.txt)

**Comment by stefanberger** [comment] 2021-07-21 18:38
Does EDK2 let you into a menu and is there some sort of TPM 2 support visible in one of those menu items?
Can you try to run Linux and see whether that shows proper /dev/tpm0 and /dev/tpmrm0. Just for sanity...

**Comment by jeremyd2019** [comment] 2021-07-21 19:23
> Does EDK2 let you into a menu and is there some sort of TPM 2 support visible in one of those menu items?

Yes. with the qemu-efi-aarch64 from experimental.  And it shows different things after swtpm_setup than it does before.

> Can you try to run Linux and see whether that shows proper /dev/tpm0 and /dev/tpmrm0. Just for sanity...

I tried to run debian testing.  I couldn't figure out how to get it to see the tpm though (maybe that's the problem).  I could see it in the ACPI tables in dmesg output, but any tpm module I tried to load didn't seem to do anything.

[swtpm-debian.txt](https://github.com/stefanberger/swtpm/files/6858281/swtpm-debian.txt)

In this log, I put blank lines before I selected to start booting debian from grub (there was some activity there, so either grub or linux was talking to it), and more blank lines before shutting down.

**Comment by stefanberger** [comment] 2021-07-21 19:45
We only support the TIS on QEMU. So my guess would be that `modprobe tpm_tis` should activate the TPM driver on aarch64 as well. Otherwise maybe there's another driver with `tis` in the name that you could try.

**Comment by jeremyd2019** [comment] 2021-07-21 20:06
I did that and it didn't do anything, so I'm guessing something's wrong on linux too

**Comment by stefanberger** [comment] 2021-07-21 20:07
Please write with which version of QEMU you tried it...

**Comment by jeremyd2019** [comment] 2021-07-21 20:09
qemu-system-arm 1:5.2+dfsg-10+b2 with qemu-efi-aarch64 2021.05-1

**Comment by jeremyd2019** [comment] 2021-07-21 20:19
```

root@debian:~# find /lib/modules -name \*tis\*
/lib/modules/5.10.0-7-arm64/kernel/net/netfilter/xt_statistic.ko
/lib/modules/5.10.0-7-arm64/kernel/drivers/char/tpm/tpm_tis_core.ko
/lib/modules/5.10.0-7-arm64/kernel/drivers/char/tpm/tpm_tis_spi.ko
/lib/modules/5.10.0-7-arm64/kernel/drivers/media/pci/mantis
/lib/modules/5.10.0-7-arm64/kernel/drivers/media/pci/mantis/mantis.ko
/lib/modules/5.10.0-7-arm64/kernel/drivers/media/pci/mantis/mantis_core.ko
root@debian:~# modprobe tpm_tis_core 
root@debian:~# modprobe tpm_tis_spi
root@debian:~# dmesg | grep -i tpm
[    0.000000] efi: SMBIOS 3.0=0x7bed0000 TPMFinalLog=0x78110000 MEMATTR=0x7a855018 ACPI 2.0=0x78100018 MOKvar=0x7908a000 TPMEventLog=0x77c96018 MEMRESERVE=0x780f9298 
[    0.000000] ACPI: TPM2 0x000000007810E818 00004C (v04 BOCHS  BXPCTPM2 00000001 BXPC 00000001)
root@debian:~# ls -l /dev/tpm*
ls: cannot access '/dev/tpm*': No such file or directory
```

**Comment by stefanberger** [comment] 2021-07-21 20:31
I don't have an aarch64 host, so it's bit more difficult to work on aarch64. I **may** try with some Fedora raw image I downloaded (https://getfedora.org/en/workstation/download/)... though I now looked at recent Fedora builds and they don't seem to have the plain tpm_tis either: https://koji.fedoraproject.org/koji/rpminfo?rpmID=26859144

Let me send an email to Eric Auger from RedHat. He did the aarch64 TPM work.

**Comment by jeremyd2019** [comment] 2021-07-21 21:12
Thanks.  As you can probably tell, I have no idea where to go with this, and barely have any idea about TPM at all.  Just that the Windows aarch64 vm Microsoft provided (https://www.microsoft.com/en-us/software-download/windowsinsiderpreviewARM64) did update to Windows 11 preview previously, but now won't update a fresh copy due to not having TPM 2.0.  I am currently trying to "reset" the Windows 11 install I got before and make a clean image I can use to test, but I'd like to be able to update also, especially if the next Windows 11 build decides not to install due to this.

**Comment by eauger** [comment] 2021-07-22 13:53
Hi Jeremu, Stefan,

I tried again with a fed33 guest and latest qemu. You should get on guest dmesg something like:
[root@localhost boot]# dmesg | grep TPM
[    0.000000] ACPI: TPM2 0x000000083C17E718 00004C (v04 BOCHS  BXPC     00000001 BXPC 00000001)
[    7.376889] tpm_tis MSFT0101:00: 2.0 TPM (device-id 0x1, rev-id 1)

By the way on my side I also get this:
[    7.379455] tpm tpm0: A TPM error (256) occurred attempting the self test
[    7.380967] tpm tpm0: starting up the TPM manually

./char/tpm/tpm_tis.c should be the driver in use. Compiled with CONFIG_TCG_TIS. This is not the SPI flavor. I am not sure the right driver is enabled in your linux kernel? As for windows setup, I am not familiar with it unfortunately. in qemu 5.2 you should have the TPM_TIS_DEVICE pieces. I also saw you used the enabled EDK2 FW so I don't have any idea atm. Your swtpm cmd line matches what I am using.

Thanks

Eric

**Comment by stefanberger** [comment] 2021-07-22 14:26
@eauger 
> By the way on my side I also get this:
> [ 7.379455] tpm tpm0: A TPM error (256) occurred attempting the self test
> [ 7.380967] tpm tpm0: starting up the TPM manually

This is not core to this problem, nevertheless we need to fix this. Most likely you somehow got an older version of libtpms running than you did before or some other corruption occurred.

Are you starting the VM with libvirt? If so, have a look at `/var/log/swtpm/libvirt/qemu/<vm name>-swtpm.log`. You may need to remove the TPM state file directory `/var/lib/libvirt/swtpm/<vm uuid>` and then start the VM.
If you started it from command line just clear all files from the directory you passed as tpmstate dir.

**Comment by jeremyd2019** [comment] 2021-07-22 17:32
> ./char/tpm/tpm_tis.c should be the driver in use. Compiled with CONFIG_TCG_TIS. This is not the SPI flavor. I am not sure the right driver is enabled in your linux kernel? As for windows setup, I am not familiar with it unfortunately. in qemu 5.2 you should have the TPM_TIS_DEVICE pieces. I also saw you used the enabled EDK2 FW so I don't have any idea atm. Your swtpm cmd line matches what I am using.

I was just using the weekly iso for Debian testing arm64 netinst.  I could try with fedora, but it sounds like you're already doing that.  Let me know if it would be helpful for me to try that.

Maybe whatever the error is that you got is related, or maybe Windows is asking swtpm things it doesn't know about (like the unexpected PCRs)?

**Comment by stefanberger** [comment] 2021-07-22 18:37
> Maybe whatever the error is that you got is related, or maybe Windows is asking swtpm things it doesn't know about (like the unexpected PCRs)?

There are no such errors visible in your logs. I think this is failing on a different level.

**Comment by stefanberger** [comment] 2021-07-22 20:46
So for the record. I tried to run an aarch64 VM in emulation mode. I ended up downloading both iso and raw image from [here](https://getfedora.org/en/workstation/download/). I could not get into a prompt in user single mode on the raw image. The root account is locked. I could not figure out how to log in otherwise. so I tried to use the cdrom.

To start the swtpm I ran this here:
```
mkdir /tmp/myvtpm1
/usr/share/swtpm/swtpm-create-user-config-files
swtpm_setup --tpmstate /tmp/myvtpm1 --tpm2 --create-ek-cert --create-platform-cert
while :; do swtpm socket --tpmstate dir=/tmp/mytpm1 --ctrl type=unixio,path=/tmp/mytpm1/swtpm-sock --log level=20 --tpm2; done
```

I started qemu with this command line (in emulation mode):
```
qemu-system-aarch64 --version
QEMU emulator version 6.0.90 (v5.2.0-6537-gbeb1913858)
Copyright (c) 2003-2021 Fabrice Bellard and the QEMU Project developers

qemu-system-aarch64 \
  -machine virt,gic-version=3  -m 4G  \
  -chardev socket,id=chrtpm,path=/tmp/mytpm1/swtpm-sock \
  -tpmdev emulator,id=tpm0,chardev=chrtpm \
  -device tpm-tis-device,tpmdev=tpm0 \
  -device virtio-blk-pci,drive=drv0 \
  -drive format=raw,file=./Fedora-Workstation-34-1.2.aarch64.raw,if=none,id=drv0 \
  -drive if=pflash,format=raw,file=/usr/share/qemu/edk2-aarch64-code.fd,readonly=on \
  -display sdl \
  -device ramfb -cpu cortex-a72 \
  -device usb-ehci -device usb-kbd \
  -device usb-mouse -usb -cdrom ./Fedora-Workstation-Live-aarch64-34-1.2.iso
```

The EDK2 menu looks good to me with TPM 2 support that looks like the one on x86_64. I chose to boot from UEFI Misc Device 3 (PCI 0x4), which is the cdrom.

**Comment by jeremyd2019** [comment] 2021-07-30 21:23
I found this blip of documentation. Does any of this require non-default options?
> All device models, lines or series must implement and be in compliance with the International Standard ISO/IEC 11889:2015 or the Trusted Computing Group TPM 2.0 Library and a component which implements the TPM 2.0 must be present and enabled by default.
> 
> The following requirements must be met:
> 
> • All TPM configurations must comply with local laws and regulations.
> 
> • Firmware-based components that implement TPM capabilities must implement version 2.0 of the TPM specification.
> 
> • An EK certificate must either be pre-provisioned to the TPM by the hardware vendor or be capable of being retrieved by the device during the first boot experience.
> 
> • It must ship with SHA-256 PCR banks and implement PCRs 0 through 23 for SHA-256. Note that it is acceptable to ship TPMs with a single switchable PCR bank that can be utilized for SHA-256 measurements.
> 
> • It must support TPM2_HMAC command.

**Comment by stefanberger** [comment] 2021-07-31 13:33
None of these should be a problem. We can provide a certificate using `swtpm_setup`, so that's there, and the SHA-256 PCR banks are also enabled by default. TPM2_HMAC is also supported. Also, we know it works on Windows in an x86_64 VM. Someone with deeper knowledge would have to investigate this on an aarch64 host and have access to Windows for aarch64, which isn't easy to get as it seems.

**Comment by jeremyd2019** [comment] 2021-07-31 20:11
> Someone with deeper knowledge would have to investigate this on an aarch64 host and have access to Windows for aarch64, which isn't easy to get as it seems.

I can't help with deeper knowledge, but Windows for aarch64 can be gotten from https://www.microsoft.com/en-us/software-download/windowsinsiderpreviewARM64 with a Microsoft account enrolled in the insider program

**Comment by stefanberger** [comment] 2021-08-01 00:33
I posted this now on qemu-devel: https://lists.gnu.org/archive/html/qemu-devel/2021-07/msg07376.html

**Comment by stefanberger** [comment] 2021-08-01 00:55
@eauger 
> By the way on my side I also get this:
> [ 7.379455] tpm tpm0: A TPM error (256) occurred attempting the self test
> [ 7.380967] tpm tpm0: starting up the TPM manually

Actually ... this error code 0x100 means:
```
tssreturncode 0x100
TPM_RC_INITIALIZE - TPM not initialized by TPM2_Startup or already initialized
```
I don't know what firmware you used but likely it doesn't have TPM 2 support.
Per this code here it will then send TPM2_STARTUP() to the TPM and send the selftest command again: https://elixir.bootlin.com/linux/latest/source/drivers/char/tpm/tpm2-cmd.c#L731

As long as the resulting /dev/tpm0 is working it should be fine:
```
tsspcrread -ha 10
count 1 pcrUpdateCounter 92
 digest legnth 32
 43 02 64 dd 39 79 ee b2 4a 8 cf 86 ac 7f d5 7b
 [...]
```

**Comment by stefanberger** [comment] 2021-08-02 14:10
@jeremyd2019 Did you check whether there are any Windows updates that you could install?

**Comment by jeremyd2019** [comment] 2021-08-02 17:31
Unfortunately without a TPM the preview image cannot update to the newer Windows 11 preview.  That's why I was looking to emulate a TPM in the first place.

**Comment by stefanberger** [comment] 2021-08-02 17:48
>  the newer Windows 11 preview

So there is a 'newer Windows 11 preview?' Maybe that could solve this issue... maybe.

**Comment by jeremyd2019** [comment] 2021-08-02 23:39
Unlikely but I'll give it a try.  I'll have to use uupdump.net to get the files, because the official update won't run without a working TPM 2.0 device.

**Comment by jeremyd2019** [comment] 2021-08-03 06:09
While waiting for that, I downloaded the x86_64 version of Windows 11 and gave that a try in qemu-system-x86_64 with swtpm.  As expected, that's been doing a good amount of talking to swtpm during the install, and it shows as "working properly" in device manager.  So whatever is going on is definitely ARM64 specific, not due to Windows 11.

**Comment by jeremyd2019** [comment] 2021-08-03 06:25
The latest Windows 11 22000.100 build is still saying "The I/O device is configured incorrectly or the configuration parameters to the driver are incorrect." on ARM64.

**Comment by eauger** [comment] 2021-08-03 09:17
PPI is not supported by the TPM TIS device while it is on x86. Could that be an issue?

**Comment by stefanberger** [comment] 2021-08-03 11:49
> PPI is not supported by the TPM TIS device while it is on x86. Could that be an issue?

That's hard to say without logs or knowing what 'it' is looking for. But PPI is primarily used to set certain state of the TPM following a reboot. It's not required to use the TPM. That error code 10 in the screenshot above is unfortunately I bit too generic.

**Comment by eauger** [comment] 2021-08-03 13:01
on ARM we are not supporting TPM 1.2. Just to make sure are you using --tpm2 along with swtpm (or is it the default?). In your first edit, I don't see this option?

**Comment by jeremyd2019** [comment] 2021-08-03 17:59
Yes, I'm using --tpm2.

If anybody knows how to get better info from Windows, I'd be happy to try.  I noticed they have a TpmDiagnostics tool now, I will try some of those options.  I tried PlatformType but it gave an error that no supported TPM2 was found.

**Comment by stefanberger** [comment] 2021-08-03 18:07
`tpm.msc` is an executable you could try. Kernel logs would be better. Maybe there's something in the 'Event Viewer' (left click on windows sign and type 'event viewer')?

**Comment by jeremyd2019** [comment] 2021-08-03 19:26
Well, I managed to get this log (in two formats), but I don't know that it means anything to anybody but Microsoft...

[dumpfile.csv](https://github.com/stefanberger/swtpm/files/6926602/dumpfile.csv)
[dumpfile.xml.txt](https://github.com/stefanberger/swtpm/files/6926603/dumpfile.xml.txt)

**Comment by jeremyd2019** [comment] 2021-08-03 19:46
Seeing error codes
0x800710DF = `ERROR_DEVICE_NOT_AVAILABLE`
0x80290401 = `TPM_E_PCP_DEVICE_NOT_READY`
0x8028400F = `TBS_E_TPM_NOT_FOUND`

**Comment by jeremyd2019** [comment] 2021-08-03 19:54
Here's the original etl file before I tried to convert it with `tracerpt`
[TPM.zip](https://github.com/stefanberger/swtpm/files/6926735/TPM.zip)

**Comment by stefanberger** [comment] 2021-08-03 19:55
We would need someone who either knows the requirements of the device and can tell us what we are missing or someone who can make modifications to QEMU to try things out. Enabling just printf's on reads from the TIS interface or writes to it is one thing to try out. Enabling PPI is another thing. It's hard to guess from these error messages what the cause may be.

**Comment by naitaku** [comment] 2021-08-13 14:32
Hi, I'm facing the same issue. 
I think that the memory range for the TPM 2.0 device may be a problem.
It is mapped to 0x0C000000 with the current aarch64 machine, but I think it should be 0xFED40000 according to the TPM TIS specification.

I tried to modify the Qemu source code to fix the memory range, but it didn't work...
PlatformBus is mapped to 0x0C00000 in hw/arm/virt.c. I changed it to 0xFED40000 and Qemu was not able to boot with the message, "qemu-system-aarch64: -device tpm-tis-device,tpmdev=tpm0: Platform Bus: Can not fit MMIO region of size 5000".

<img width="413" alt="Screen Shot 2021-08-13 at 23 10 50" src="https://user-images.githubusercontent.com/1659642/129371566-f34fc664-dea3-48b1-9453-7420def23836.png">

**Comment by stefanberger** [comment] 2021-08-13 15:37
I guess neither edk2 nor Linux mind finding the TIS at a non-standard address but Windows doesn't accept it.

**Comment by eauger** [comment] 2021-08-14 07:10
Yes the ARM TPM-TIS-SYSBUS device matches the "tcg,tpm-tis-mmio" compat on Linux. As a platform bus it is allowed to be instantiated everywhere in the memory map (see for instance linux Documentation/devicetree/bindings/security/tpm/tpm_tis_mmio.txt). On ARM VIRT the RAM starts at 1GB and its end depends on the memory option, allowed to go up to TB. So the ARM virt memory map cannot accomodate this fixed 0xFED0.0000 location.

**Comment by stefanberger** [comment] 2021-08-15 05:47
It feels like Windows may end up forcing the QEMU implementation of a TPM interface on another bus, possibly SPI or IC2, unless Microsoft adapts their driver.
Which other TPM interface drivers than the TIS would work on a real aarch64 system? The following ones seem to be using ACPI in some form:
- https://elixir.bootlin.com/linux/latest/source/drivers/char/tpm/tpm_tis_synquacer.c
- https://elixir.bootlin.com/linux/latest/source/drivers/char/tpm/tpm_tis_i2c_cr50.c

**Comment by jeremyd2019** [comment] 2021-09-17 20:48
https://www.notebookcheck.net/Windows-11-Insider-Preview-Build-22000-194-blocks-Virtual-Machines-that-lack-TPM-2-0.562358.0.html

I haven't tried it yet, so I don't know if this really breaks any of the workarounds.

**Comment by stefanberger** [comment] 2021-09-17 20:54
> I haven't tried it yet, so I don't know if this really breaks any of the workarounds to run without TPM 2.

I didn't know there were 'workarounds'...

**Comment by jeremyd2019** [comment] 2021-09-17 23:13
There has been a workaround to bypass the check for TPM 2 during setup.  Some rather confusing press reports last month suggested they'd remove the setup checks from the ISO installers, allowing install on "unsupported" hardware at your own risk, but potentially updates may not be available for unsupported hardware.  Of course, I'm sure all of this was in the context of x86_64, and arm64 is generally not considered other than on hardware that ships with Windows pre-installed.

Previously, they were supposed to exclude virtual machines from the hardware requirements, but that never seemed to happen for arm64 VMs (at least under QEMU).

**Comment by ms-mahuber** [comment] 2022-01-14 18:26
I've hit this problem as well - before finding this thread, I've tried various things but device manager always shows the TPM2 device warning as referenced above (Win10).

On my setup I got a Linux aarch64 guest with swtpm TPM2 emulation fully working - without showing the selftest error message at guest boot. 

Has there been any traction or new insights on this in the meantime?

**Comment by stefanberger** [comment] 2022-01-14 18:41
I haven't seen any development on aarch64 QEMU on something related to what I mentioned above. I **think** this is what is needed:

> It feels like Windows may end up forcing the QEMU implementation of a TPM interface on another bus, possibly SPI or IC2, unless Microsoft adapts their driver.
Which other TPM interface drivers than the TIS would work on a real aarch64 system? The following ones seem to be using ACPI in some form:
>
>    https://elixir.bootlin.com/linux/latest/source/drivers/char/tpm/tpm_tis_synquacer.c
>    https://elixir.bootlin.com/linux/latest/source/drivers/char/tpm/tpm_tis_i2c_cr50.c

**Comment by willcohen** [comment] 2022-08-02 14:02
My knowledge of ACPI, BIOS, hardware emulation, and the TPM spec in general is rather low (full transparency, back when I spent too much time as a highschooler building computers, I remember my motherboard's Athlon processor slot RAM DIMMs, and used PCI slots for most of the cards and an ISA slot for the Gravis Ultrasound, and ever since stuff started being hard-soldered the details of hardware started to go over my head), but I'd like to do what I can to further this and get a solution eventually landed into QEMU. Am I correctly understanding the identified problem and proposed solution?

- Currently, QEMU uses `swtpm` to emulate a TPM module using the `TIS` interface, currently implemented on ISA via https://gitlab.com/qemu-project/qemu/-/blob/master/hw/tpm/tpm_tis_isa.c, implementing https://trustedcomputinggroup.org/wp-content/uploads/TCG_PCClientTPMInterfaceSpecification_TIS__1-3_27_03212013.pdf. Something about this implementation doesn't make sense on arm64 due to memory limit issues. @stefanberger has identified two potential examples in the linux kernel drivers that implement the TIS using ACPI in some form, and has noted that it needs to be implemented on a new bus, like SPI or I2C. I assume that means that QEMU will need a new file, like `tpm_tis_isa.c` or perhaps modifications to `tpm_tis_sysbus.c`, that instead works on `_spi` or `_i2c`. Do I have this right?
- All the files noted above, in their comments, refer to implementation of the TPM TIS for TPM 2 spec. I notice that there is also an ACPI spec, which dates to 2021 rather than 2013, at https://trustedcomputinggroup.org/wp-content/uploads/TCG_ACPIGeneralSpec_v1p3_r8_pub.pdf. Does this additional specification matter at all for our purposes or is it irrelevant for implementation?

Without fully understanding what I'm getting myself into, it seems like the discussion of solutions above might include any of the following:
- Creating a `SPI` or `IC2` alternative to the `ISA` implementation of the TIS in qemu.
- Further implementing portions of the ACPI spec document to deal with memory limit assumptions in `sysbus` that aren't quite correct, and dealing with the additional bus via that.

**Comment by stefanberger** [comment] 2022-08-05 08:55
> I assume that means that QEMU will need a new file, like tpm_tis_isa.c or perhaps modifications to tpm_tis_sysbus.c, that instead works on _spi or _i2c. Do I have this right?

It is my guess that we should use either one of these buses, but I don't know whether one is better than the other and their status in QEMU. If there was existing support for EDK2 (UEFI) for ARM Hardware with hardware TPM 2 I would suggest to follow the bus they use there but there's no support in EDK2 for ARM...

**Comment by gvaldezd** [comment] 2022-08-05 15:29
> > I assume that means that QEMU will need a new file, like tpm_tis_isa.c or perhaps modifications to tpm_tis_sysbus.c, that instead works on _spi or _i2c. Do I have this right?
> 
> It is my guess that we should use either one of these buses, but I don't know whether one is better than the other and their status in QEMU. If there was existing support for EDK2 (UEFI) for ARM Hardware with hardware TPM 2 I would suggest to follow the bus they use there but there's no support in EDK2 for ARM...

Hi, I replaced the edk2-aarch64-code.fd file (path: /Applications/UTM.app/Contents/Resources/qemu) used by UTM (3.2.4) with a new file EDK2 (builded using another Linux VM following these instructions [)](https://www.kraxel.org/blog/2022/05/edk2-virt-quickstart/) both VM's are installed in a Mac M1 (MacOS12.5 Monterey) with Secure Boot option enabled, the UEFI shows a TPM device with different settings (those options are not shown in original UTM file).

<img width="328" alt="EDK2_TPM" src="https://user-images.githubusercontent.com/13753776/183107008-83d5be28-533e-4aa2-9c44-ddca187d71fc.png">

However, Windows 11 boots fine but could not start the tpm device using 0XC000000 memory address. 

I'm not an expert, just wanted to share that EDK2 source (tianocore/edk2) will work with the UTM.app in a Mac M1

**Comment by stefanberger** [comment] 2022-08-05 15:36
@gvaldezd Right, Linux on ARM **VM** works with existing drivers and it's Windows on ARM in a **VM** that doesn't work and may require a different bus. Now what I would be looking for is running EKD2 on ARM **hardware** with TPM 2 support and see what kind of bus that is using.

**Comment by stefanberger** [comment] 2022-08-08 00:58
There's now an RFC patch for SPI bus support for TPM TIS: https://lists.nongnu.org/archive/html/qemu-devel/2022-08/msg00401.html

**Comment by willcohen** [comment] 2022-08-09 21:07
I can't immediately apply that RFC patch on top of the two RFC patches it builds upon submitted a week or two earlier without some of the hunks failing -- I may have to do a little cherry-picking to get them to apply on top of one another cleanly, and it may be that I'm currently applying on top of 7.0 and need to use HEAD. Once I get those wrinkles resolved I'll try to see if this works with Windows 11.

**Comment by stefanberger** [comment] 2022-09-07 17:30
> There's now an RFC patch for SPI bus support for TPM TIS: https://lists.nongnu.org/archive/html/qemu-devel/2022-08/msg00401.html

I applied these patches now to a branch here: https://github.com/stefanberger/qemu-tpm/tree/v7.1.0-tpm-aarch64

It builds fine but finding a command line for QEMU for getting this device to work is a challenge of its own. How does one get an SSI bus?

**Comment by willcohen** [comment] 2022-09-09 13:01
If I'm reading this generic spi thread (https://lists.gnu.org/archive/html/qemu-devel/2022-08/msg00793.html) correctly, I guess it's only been implemented for the aspeed machine types and it'll need another round before it's generic enough for other machines (would we be targeting `virt` for a windows VM?)

@chen-iris: do you think it's feasible to try to get Windows 11 booted on an aspeed QEMU machine (and therefore using your TPM RFC), or would we need to hold tight until the implementation is further worked out before testing and helping out?

**Comment by stefanberger** [comment] 2023-04-20 00:16
@willcohen FYI, also for aspeed machine types: https://lists.nongnu.org/archive/html/qemu-devel/2023-04/msg02199.html

**Comment by willcohen** [comment] 2023-04-24 15:36
Lovely. Will try this out!

**Comment by osy** [comment] 2023-07-09 07:30
I've logged the writes from QEMU (secure boot enabled):
[swtpm_io.log](https://github.com/stefanberger/swtpm/files/11994655/swtpm_io.log)

I've also have a UTM log combining SWTPM, SPICE, and QMP:
[swtpm_utm.log](https://github.com/stefanberger/swtpm/files/11994656/swtpm_utm.log)

I'm not sure why the current theory is on the TPM interface. I think VMware/Parallels have TPM 2.0 emulation working, has anyone checked what interface they are using?

**Comment by idarek** [comment] 2023-07-09 07:32
Could you explain how and what you want to check and will do that in VMware.

**Comment by osy** [comment] 2023-07-11 00:51
Okay so I made progress! But not in getting TPM 2.0 working on QEMU but on breaking TPM 2.0 in VMware! Okay I know that doesn't sound impressive but at least we know what the issue is.

First, let's look at the TPM2 ACPI table for a VMWare Fusion VM:

```
[000h 0000   4]                    Signature : "TPM2"    [Trusted Platform Module hardware interface table]
[004h 0004   4]                 Table Length : 0000004C
[008h 0008   1]                     Revision : 03
[009h 0009   1]                     Checksum : F0
[00Ah 0010   6]                       Oem ID : "VMWARE"
[010h 0016   8]                 Oem Table ID : "VMW_TPM2"
[018h 0024   4]                 Oem Revision : 00000001
[01Ch 0028   4]              Asl Compiler ID : "VMW "
[020h 0032   4]        Asl Compiler Revision : 00000001

[024h 0036   4]                     Reserved : 00000000
[028h 0040   8]              Control Address : 00000000FFFFF040
[030h 0048   4]                 Start Method : 00000008

Raw Table Data: Length 76 (0x4C)

    0000: 54 50 4D 32 4C 00 00 00 03 F0 56 4D 57 41 52 45  // TPM2L.....VMWARE
    0010: 56 4D 57 5F 54 50 4D 32 01 00 00 00 56 4D 57 20  // VMW_TPM2....VMW 
    0020: 01 00 00 00 00 00 00 00 40 F0 FF FF 00 00 00 00  // ........@.......
    0030: 08 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  // ................
    0040: 00 00 01 00 00 00 FE FF 00 00 00 00              // ............
```

Compare that with QEMU:

```
[000h 0000   4]                    Signature : "TPM2"    [Trusted Platform Module hardware interface table]
[004h 0004   4]                 Table Length : 0000004C
[008h 0008   1]                     Revision : 04
[009h 0009   1]                     Checksum : 91
[00Ah 0010   6]                       Oem ID : "BOCHS "
[010h 0016   8]                 Oem Table ID : "BXPC    "
[018h 0024   4]                 Oem Revision : 00000001
[01Ch 0028   4]              Asl Compiler ID : "BXPC"
[020h 0032   4]        Asl Compiler Revision : 00000001

[024h 0036   2]               Platform Class : 0000
[026h 0038   2]                     Reserved : 0000
[028h 0040   8]              Control Address : 0000000000000000
[030h 0048   4]                 Start Method : 06 [Memory Mapped I/O]

[034h 0052  12]            Method Parameters : 00 00 00 00 00 00 00 00 00 00 00 00
[040h 0064   4]           Minimum Log Length : 00010000
[044h 0068   8]                  Log Address : 000000023C4C0000

Raw Table Data: Length 76 (0x4C)

    0000: 54 50 4D 32 4C 00 00 00 04 91 42 4F 43 48 53 20  // TPM2L.....BOCHS 
    0010: 42 58 50 43 20 20 20 20 01 00 00 00 42 58 50 43  // BXPC    ....BXPC
    0020: 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  // ................
    0030: 06 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  // ................
    0040: 00 00 01 00 00 00 4C 3C 02 00 00 00              // ......L<....
```

The main difference is that VMWare uses the CRB interface (start method 8 = "Command Response Buffer Interface with the ACPI Start Method" and start method 6 = "Memory mapped I/O Interface (TIS 1.2+Cancel)")

Another observation is that Windows doesn't even _attempt_ to communicate with the TPM 2.0 at all under QEMU. The logs I posted above all takes place before winload.efi and there's no I/O access to the TPM interface afterwards.

So how do you force VMWare Fusion to use CRB? Through some reverse engineering and guessing, I found that in the .vmx config file, you can add `vtpm.crb.hw = "FALSE"` to force VMWare to use a TIS interface. Once that's done, we see the ACPI table matches the start method 6 and that device manager shows Code 10 with error 0xC0000182 (the same as QEMU).

So why don't we use CRB in QEMU? In fact the CRB device is already implemented in QEMU and with a little hackery with the base address we can force it to load on ARM64 VMs. It's even pretty straightforward to add a SysBus device variant for it.

Unfortunately, the luck ends here. We begin to see Windows make I/O access on the CRB device (progress!) but the VM crashes in the tpm.sys driver when it hits this line:

```
       1c0022abc 21 21 43 29     ldp        w1,w8,[x9, #0x18]
```

This is an attempted 64-bit access on the TPM MMIO interface. Currently, this causes the HVF backend to crash with `assert(isv)` because when ARM64 aborts on a LDP, it does NOT decode the faulting instruction for you. This means, you (the hypervisor) must manually decode and emulate the instruction to figure out what the intended effects are. Currently, QEMU does not have this capability although I believe the KVM backend might support it (although I do not have a ARM64 KVM system to test with currently).

(P.S: Even after working around this crash, it's unknown if everything will "just work" or if there's other issues as well but this is currently blocking progress.)

**Comment by osy** [comment] 2023-07-11 02:49
Okay, I got it working with some insane amount of "not shippable" code including a hard coded STP detection and patcher in HVF backend. However, it shows that CRB interface works. Hopefully, I'll have something on the UTM QEMU fork posted soon.

**Comment by stefanberger** [comment] 2023-07-11 15:06
> However, it shows that CRB interface works.

You mean the CRB interface works with the method as advertised by ACPI? Is the memory range the issue ?

**Comment by osy** [comment] 2023-07-11 16:10
Yeah CRB as advertised by the ACPI table plus my QEMU CRB sysbus driver.

I don’t know what the evidence there is for the MMIO range being an issue but I’ve reversed engineered the startup code in tpm.sys and found no evidence of any checks on an allowed range or anything like that. If you want to confirm, perhaps change the hard coded address on an x86_64 QEMU vm and see if Windows produces the same error? My hunch says no.

The fact that VMware’s TIS device produces the same error on ARM64 Windows means that it’s probably a Microsoft issue (they would have the resources to fix it).

**Comment by stefanberger** [comment] 2023-07-11 16:20
> I don’t know what the evidence there is for the MMIO range being an issue but I’ve reversed engineered the startup code in

I don't have evidence about it nor am I an expert on aarch64 allowed MMIO ranges, but I can point you to a comment above regarding this: https://github.com/stefanberger/swtpm/issues/493#issuecomment-898851156

**Comment by osy** [comment] 2023-07-11 17:06
Yeah I’ve read that comment but don’t understand the connection.

**Comment by stefanberger** [comment] 2023-08-17 01:57
I am closing this issue now since it's clearly a QEMU issue.

**Closed by stefanberger** 2023-08-17 01:57 UTC
Labels: Windows, aarch64, QEMU Issue
