### ISSUE TITLE
Permission denied creating emulated tpm under Virtual Machine Manager-Permission denied

### ISSUE THREAD

**Issue by FreedomFaighter** [stefanberger/swtpm#297] opened 2020-08-09 10:17 UTC
$qemu-x86_64 --version
qemu-x86_64 version 5.0.0
$swtpm --version
TPM emulator version 0.3.2, Copyright (c) 2014 IBM Corp.
When I try to add an emulated tpm I get
swtpm-localca: touch: cannot touch '/var/lib/swtpm-localca/.lock.swtpm-localca': Permission denied
Virtual machine is under the User Session
I've tried add my user and qemu to the tss group which hasn't worked
chmod 775 doesn't allow it
chmod 777 does (but is bad for obvious reasons)
Guess my question is and it might be a virt-manager question which user do I add to tss group to be able to touch this file?

**Comment by stefanberger** [comment] 2020-08-09 23:43
Are you trying to start a VM with an attached TPM 1.2 or TPM 2? I suppose it's a TPM 1.2. Can you give a bit more detail about your environment, like distro you are using? This may help others later. The problem is typically a permission problem on the libvirt level and the following swtpm related entries may need to be adapted to what `tcsd` expects:

```
# User for the swtpm TPM Emulator
#
# Default is 'tss'; this is the same user that tcsd (TrouSerS) installs
# and uses; alternative is 'root'
#
#swtpm_user = "tss"
#swtpm_group = "tss"
```

Also the ownership of `/var/lib/swtpm-localca`  and contents has to be set accordingly. For Fedora it's `tss:tss` following the above entries.

```
# cd /var/lib
# ls -l | grep swtpm-localca
drwxr-xr-x.  2 tss            tss               4096 Feb 26 07:50 swtpm-localca
# ls -l /var/lib/swtpm-localca
total 28
-rw-r--r--. 1 tss tss    3 Aug  6 16:04 certserial
-rw-r--r--. 1 tss tss 1505 Dec 27  2018 issuercert.pem
-rw-r-----. 1 tss tss 8183 Dec 27  2018 signkey.pem
-rw-r--r--. 1 tss tss 1468 Dec 27  2018 swtpm-localca-rootca-cert.pem
-rw-r-----. 1 tss tss 8177 Dec 27  2018 swtpm-localca-rootca-privkey.pem
```

**Comment by stefanberger** [comment] 2020-08-10 00:32
@FreedomFaighter  Sorry, the above description is for non-User Sessions. For user sessions you may not want to add the user to the tss group because that could give that user direct access to TPM devices. Instead, you may want to follow the instructions shown here and create configuration files in the user's `XDG_CONFIG_HOME`

https://github.com/stefanberger/swtpm/blob/master/man/man8/swtpm_setup.pod#example-usage

**Comment by stefanberger** [comment] 2020-08-19 18:50
The master branch now has a script that creates the configuration files necessary for a User Session:

```
$ /usr/share/swtpm/swtpm-create-user-config-files --overwrite
Writing /home/stefanb/.config/swtpm_setup.conf.
Writing /home/stefanb/.config/swtpm/swtpm-localca.conf.
Writing /home/stefanb/.config/swtpm/swtpm-localca.options.
```

**Comment by FreedomFaighter** [comment] 2020-08-20 20:33
thanks. I'll git it a go soon and report results

**Comment by stefanberger** [comment] 2020-09-09 21:34
With swtpm-0.4.0 there's no need anymore to add the user to a group and swtpm_setup should be able to run under any user for as long as the permissions to directories and files are appropriately set.

**Comment by stefanberger** [comment] 2020-10-02 18:15
Is this still an issue with swtpm-0.4.0? It shouldn't be. If not, let's close this issue.

**Comment by stefanberger** [comment] 2020-10-06 20:53
Closing it for now since it shouldn't be an issue anymore with recent versions of swtpm that has gotten rid of `tcsd`.

**Closed by stefanberger** 2020-10-06 20:53 UTC
