### ISSUE TITLE
Error starting domain: Unable to find 'swtpm_setup' binary in $PATH: No such file or directory

### ISSUE THREAD

**Issue by TheJags** [stefanberger/swtpm#463] opened 2021-06-16 18:38 UTC
I'm getting this error while trying to install Windows 10 (Guest OS) under QEMU/KVM on Ubuntu MATE 21.04 (Host OS). The error shows up the moment I click `Run` on `Windows 10` virtual machine. So, the installation doesn't even start at all. 

One of the guide I'm using have steps to use `TPM`: `https://matteocroce.medium.com/windows-as-qemu-guest-a115a56043b6`

````
Error starting domain: Unable to find 'swtpm_setup' binary in $PATH: No such file or directory

Traceback (most recent call last):

  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 65, in cb_wrapper
    callback(asyncjob, *args, **kwargs)
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 101, in tmpcb
    callback(*args, **kwargs)
  File "/usr/share/virt-manager/virtManager/object/libvirtobject.py", line 57, in newfn
    ret = fn(self, *args, **kwargs)
  File "/usr/share/virt-manager/virtManager/object/domain.py", line 1329, in startup
    self._backend.create()
  File "/usr/lib/python3/dist-packages/libvirt.py", line 1353, in create
    raise libvirtError('virDomainCreate() failed')
    
libvirt.libvirtError: Unable to find 'swtpm_setup' binary in $PATH: No such file or directory
````
![swtpm_error](https://user-images.githubusercontent.com/47936415/122273648-4d12eb80-ceff-11eb-9f19-b87e499b0276.jpg)

I've installed `swtpm` from this Launchpad PPA: `https://launchpad.net/~stefanberger/+archive/ubuntu/swtpm`

The `TPM` options I have selected on `virt-manager`
````
Add hardware > TPM:

Model: CRB
Backend: Emulated device
Version: 2.0
````

````
OS: Ubuntu MATE 21.04 Hirsute
Kernel: 5.13.0-051300rc6-generic
QEMU: 1:5.2+dfsg-9ubuntu3
libvirt0: 7.0.0-2ubuntu2
virt-manager: 1:3.2.0-3

swtpm: 0.6.0-1
swtpm-libs: 0.6.0-1
libtpms0: 0.8.3-1
libtss2-tcti-swtpm0: 3.0.3-2ubuntu1
````

Thanks a lot.

**Comment by stefanberger** [comment] 2021-06-16 19:16
Please also install the swtpm-tools package. That file should provide `swtpm_setup` along with other necessary ones in `/usr/bin`.

```
# dpkg -c  swtpm-tools_0.6.0_amd64.deb
drwxr-xr-x root/root         0 2021-06-07 14:00 ./
drwxr-xr-x root/root         0 2021-06-07 14:00 ./etc/
-rw-r--r-- root/root       180 2021-06-07 14:00 ./etc/swtpm-localca.conf
-rw-r--r-- root/root        76 2021-06-07 14:00 ./etc/swtpm-localca.options
-rw-r--r-- root/root       200 2021-06-07 14:00 ./etc/swtpm_setup.conf
drwxr-xr-x root/root         0 2021-06-07 14:00 ./usr/
drwxr-xr-x root/root         0 2021-06-07 14:00 ./usr/bin/
-rwxr-xr-x root/root     18920 2021-06-07 14:00 ./usr/bin/swtpm_bios
-rwxr-xr-x root/root     44216 2021-06-07 14:00 ./usr/bin/swtpm_cert
-rwxr-xr-x root/root     27304 2021-06-07 14:00 ./usr/bin/swtpm_ioctl
-rwxr-xr-x root/root     63560 2021-06-07 14:00 ./usr/bin/swtpm_setup
drwxr-xr-x root/root         0 2021-06-07 14:00 ./usr/share/
drwxr-xr-x root/root         0 2021-06-07 14:00 ./usr/share/doc/
drwxr-xr-x root/root         0 2021-06-07 14:00 ./usr/share/doc/swtpm-tools/
-rw-r--r-- root/root       408 2021-06-07 14:00 ./usr/share/doc/swtpm-tools/changelog.gz
-rw-r--r-- root/root      1507 2020-07-07 16:02 ./usr/share/doc/swtpm-tools/copyright
drwxr-xr-x root/root         0 2021-06-07 14:00 ./usr/share/man/
drwxr-xr-x root/root         0 2021-06-07 14:00 ./usr/share/man/man8/
-rw-r--r-- root/root      3335 2021-06-07 14:00 ./usr/share/man/man8/swtpm-localca.8.gz
-rw-r--r-- root/root      2866 2021-06-07 14:00 ./usr/share/man/man8/swtpm-localca.conf.8.gz
-rw-r--r-- root/root      2150 2021-06-07 14:00 ./usr/share/man/man8/swtpm-localca.options.8.gz
-rw-r--r-- root/root      3192 2021-06-07 14:00 ./usr/share/man/man8/swtpm_bios.8.gz
-rw-r--r-- root/root      3625 2021-06-07 14:00 ./usr/share/man/man8/swtpm_cert.8.gz
-rw-r--r-- root/root      3636 2021-06-07 14:00 ./usr/share/man/man8/swtpm_ioctl.8.gz
-rw-r--r-- root/root      5292 2021-06-07 14:00 ./usr/share/man/man8/swtpm_setup.8.gz
-rw-r--r-- root/root      2928 2021-06-07 14:00 ./usr/share/man/man8/swtpm_setup.conf.8.gz
drwxr-xr-x root/root         0 2021-06-07 14:00 ./usr/share/swtpm/
-rwxr-xr-x root/root      2328 2021-06-07 14:00 ./usr/share/swtpm/swtpm-create-user-config-files
-rwxr-xr-x root/root     34888 2021-06-07 14:00 ./usr/share/swtpm/swtpm-localca
lrwxrwxrwx root/root         0 2021-06-07 14:00 ./usr/share/man/man8/swtpm_setup.sh.8.gz -> swtpm_setup.8.gz

```

**Comment by TheJags** [comment] 2021-06-16 19:25
@stefanberger thank you so much for the reply.

`apt` cannot find package `swtpm_setup`. Apparently it's not in your Launchpad PPA, and neither in Ubuntu Hirsute repos. How do I install it please.

Here's the output:
````
sudo apt install swtpm_setup

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package swtpm_setup
````

Here's my `/etc/apt/sources.list`:

````
deb http://us.archive.ubuntu.com/ubuntu/ hirsute main restricted universe multiverse
deb http://us.archive.ubuntu.com/ubuntu/ hirsute-updates main restricted universe multiverse
deb http://us.archive.ubuntu.com/ubuntu/ hirsute-backports main restricted universe multiverse
deb http://security.ubuntu.com/ubuntu hirsute-security main restricted universe multiverse
````

**Comment by stefanberger** [comment] 2021-06-16 19:39
It's right here: https://launchpad.net/~stefanberger/+archive/ubuntu/swtpm-focal/+packages

When you click on the twisty near swtpm you find these packages:

swtpm-tools_0.6.0-1_amd64.deb (83.1 KiB)
swtpm-tools_0.6.0-1_arm64.deb (79.4 KiB)
swtpm-tools_0.6.0-1_armhf.deb (79.0 KiB)
swtpm-tools_0.6.0-1_ppc64el.deb (84.3 KiB)
swtpm-tools_0.6.0-1_s390x.deb (78.4 KiB) 

All the repos for Xenial, Bionic, and Focal have it.

**Comment by stefanberger** [comment] 2021-06-16 19:40
Please install **swtpm-tools:**
```
apt-get -y install swtpm-tools
```

**Comment by TheJags** [comment] 2021-06-16 20:05
@stefanberger 

> Please install **swtpm-tools:**
> 
> ```
> apt-get -y install swtpm-tools
> ```

**swtpm-tools** got installed just fine. 

I also corrected another error on my part. I had:
````
deb http://ppa.launchpad.net/stefanberger/swtpm/ubuntu xenial main
````

which I changed to:

````
deb http://ppa.launchpad.net/stefanberger/swtpm-focal/ubuntu focal main
````

I can also report that, `Windows 11 Build 21996.1` installation went just fine, and Windows 11 is running fine with `Emulated TPM 2.0` and `Secure Boot` enabled in `virt-manager`.

Thank you so much :)

**Comment by stefanberger** [comment] 2021-06-16 20:15
Yeehaa! You can then close the issue if it's resolved.

**Closed** 2021-06-16 20:30 UTC

**Comment by omegahack0** [comment] 2021-11-04 08:40
Hey guys when I added deb http://ppa.launchpad.net/stefanberger/swtpm-focal/ubuntu focal main to my sources.list, then did an update I got the following error :W: GPG error: http://ppa.launchpad.net/stefanberger/swtpm-focal/ubuntu focal InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 1E9E66385D3E4D5D

**Comment by stefanberger** [comment] 2021-11-04 11:46
Did you follow the steps here? https://launchpad.net/~stefanberger/+archive/ubuntu/swtpm-focal

**Comment by Asleep-at-the-wheel** [comment] 2021-11-25 02:50
I ran into the same issue even after installing `swtpm-tools`.

For anyone who might need it, a restart of libvirtd fixed it:
`sudo systemctl restart libvirtd`

**Comment by jakubgajski** [comment] 2022-06-24 07:44
In my case helped:
- adding "/dev/tpmo rw" to /etc/apparmor.d/abstractions/libvirt-qemu
- reloading apparmor sudo service apparmor reload
(here still I had problems with TPM compatibility)
- choosing TIS TPM model.

Ubuntu 20.04.

**Comment by stefanberger** [comment] 2022-06-24 14:50
I don't see why `/dev/tpm0 rw` would help resolve this issue for swtpm_setup that has no need for `/dev/tpm0`. It looks more like a PATH issue.

**Comment by jakubgajski** [comment] 2022-06-27 07:41
I have expressed myself imprecise. Edit added to my post: use of pass-through TMP in Qemu.

**Comment by stefanberger** [comment] 2022-06-27 11:58
> I have expressed myself imprecise. Edit added to my post: use of pass-through TMP in Qemu. The error faced by TheJags is related to emulated one.

It sounds like a completely different problem then and has nothing to do with the title of this issue here: [Error starting domain: Unable to find 'swtpm_setup' binary in $PATH: No such file or directory](https://github.com/stefanberger/swtpm/issues/463#)

**Comment by jakubgajski** [comment] 2022-06-27 12:05
> > I have expressed myself imprecise. Edit added to my post: use of pass-through TMP in Qemu. The error faced by TheJags is related to emulated one.
> 
> It sounds like a completely different problem then and has nothing to do with the title of this issue here: [Error starting domain: Unable to find 'swtpm_setup' binary in $PATH: No such file or directory](https://github.com/stefanberger/swtpm/issues/463#)

I have faced exactly the same problem as the author, and I get rid of this problem the way I have stated. Yes. the title relates to swtpm, but the problem is more general. Ultimately the goal is to have Win10 up and running on Qemu VM. And I hope anyone who will find this thread like I have, will find this solution helpful.
